server:
  port: 8039
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://192.168.1.138:3306/triage_call_system_main?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    #    username: root
    #    password: leenleda2020
    url: jdbc:mysql://localhost:3306/local_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mybatis:
  mapperLocations: classpath*:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true